layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    
     - codepath-prework

social_media:
#   behance: your_username
#   dribbble: your_username
#   facebook: your_username
#   hackerrank: susususuwang
#   instagram: your_username
#   keybase: your_username
   linkedin: suwei-wang
#   mastodon: your_username
#   medium: your_username
#   stackoverflow: your_user_id/Users/sw/Desktop/personal-website/_data/social_media.yml
#   telegram: your_username
#   twitter: your_username
#   unsplash: your_username
#   vk: your_username
   website: https://swstephanie.github.io/
#   youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/5b3600551e122a3277c2c5368af2ad5725ffa9a1/topics/java/java.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
  - name: SpringBoot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png
#  - name: CSS
#    web_url: https://github.com/topics/css
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
